---
- name: Configure bashrc for root user
  hosts: all
  become: yes
  tasks:
    - name: Copy .bashrc from GitHub
      copy:
        remote_src: https://raw.githubusercontent.com/scpx-de/ansible-playbooks/main/bashrc
        dest: /root/.bashrc
        owner: root
        group: root
        mode: '0644'

