---
- hosts: all
  become: yes
  tasks:
    - name: Ensure /etc/certs/ directory exists
      file:
        path: /etc/certs/
        state: directory
        mode: '0755'

    - name: Synchronize fullchain.pem to target servers
      synchronize:
        src: /etc/letsencrypt/live/global/fullchain.pem
        dest: /etc/certs/fullchain.pem
      delegate_to: 10.1.0.102

    - name: Synchronize privkey.pem to target servers
      synchronize:
        src: /etc/letsencrypt/live/global/privkey.pem
        dest: /etc/certs/privkey.pem
      delegate_to: 10.1.0.102

