---
- hosts: all
  become: yes
  tasks:
    - name: Ensure /etc/certs/ directory exists
      file:
        path: /etc/certs/
        state: directory
        mode: '0755'

    - name: Fetch fullchain.pem from 10.1.0.102 to Ansible Controller
      fetch:
        src: /etc/letsencrypt/live/global/fullchain.pem
        dest: "/ansible_data/fullchain.pem"
        flat: yes
      run_once: true
      delegate_to: 10.1.0.102
      when: inventory_hostname == "10.1.0.102"

    - name: Fetch privkey.pem from 10.1.0.102 to Ansible Controller
      fetch:
        src: /etc/letsencrypt/live/global/privkey.pem
        dest: "/ansible_data/privkey.pem"
        flat: yes
      run_once: true
      delegate_to: 10.1.0.102

    - name: Copy fullchain.pem from Ansible Controller to target servers
      copy:
        src: "/ansible_data/fullchain.pem"
        dest: "/etc/certs/fullchain.pem"
      when: inventory_hostname != "10.1.0.102"

    - name: Copy privkey.pem from Ansible Controller to target servers
      copy:
        src: "/ansible_data/privkey.pem"
        dest: "/etc/certs/privkey.pem"
