---
- name: Kopiere Zertifikat und Key nach 10.1.0.105
  hosts: 10.1.0.105
  tasks:
    - name: Sicherstellen, dass das SSL Verzeichnis existiert
      file:
        path: /opt/mailcow-dockerized/data/assets/ssl
        state: directory
        mode: '0755'
      become: yes

    - name: Kopiere fullchain.pem von 10.1.0.102
      fetch:
        src: /etc/letsencrypt/live/global/fullchain.pem
        dest: /tmp/
      delegate_to: 10.1.0.102
      become: yes

    - name: Kopiere privkey.pem von 10.1.0.102
      fetch:
        src: /etc/letsencrypt/live/global/privkey.pem
        dest: /tmp/
      delegate_to: 10.1.0.102
      become: yes

    - name: Verschiebe fullchain.pem zu 10.1.0.105
      copy:
        src: /tmp/fullchain.pem
        dest: /opt/mailcow-dockerized/data/assets/ssl/cert.pem
      become: yes

    - name: Verschiebe privkey.pem zu 10.1.0.105
      copy:
        src: /tmp/privkey.pem
        dest: /opt/mailcow-dockerized/data/assets/ssl/key.pem
      become: yes

