---
- name: Kopiere Zertifikat und Key nach 10.1.0.105
  hosts: 10.1.0.105
  tasks:
    - name: Sicherstellen, dass das SSL Verzeichnis existiert
      file:
        path: /opt/mailcow-dockerized/data/assets/ssl
        state: directory
        mode: '0755'
      become: yes

    - name: Synchronisiere fullchain.pem von 10.1.0.102 zu 10.1.0.105
      synchronize:
        src: /etc/letsencrypt/live/global/fullchain.pem
        dest: /opt/mailcow-dockerized/data/assets/ssl/cert.pem
      delegate_to: 10.1.0.102
      become: yes

    - name: Synchronisiere privkey.pem von 10.1.0.102 zu 10.1.0.105
      synchronize:
        src: /etc/letsencrypt/live/global/privkey.pem
        dest: /opt/mailcow-dockerized/data/assets/ssl/key.pem
      delegate_to: 10.1.0.102
      become: yes
