---
- hosts: all
  become: yes
  tasks:
    - name: Check if /etc/ssl/ directory exists
      file:
        path: /etc/ssl/
        state: directory
        mode: '0755'
      become: yes

    - name: Synchronize certificates
      synchronize:
        src: /etc/letsencrypt/live/global/
        dest: /etc/ssl/
        delete: no
        rsync_opts:
          - "--exclude=*"
          - "--include=fullchain.pem"
          - "--include=privkey.pem"
      delegate_to: 10.1.0.102
      become: yes

