---
- hosts: all
  become: yes
  tasks:
    - name: Ensure /etc/ssl/ directory exists
      file:
        path: /etc/ssl/
        state: directory
        mode: '0755'

    - name: Copy fullchain.pem to target servers
      copy:
        src: /etc/letsencrypt/live/global/fullchain.pem
        dest: /etc/ssl/fullchain.pem
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      delegate_to: 10.1.0.102

    - name: Copy privkey.pem to target servers
      copy:
        src: /etc/letsencrypt/live/global/privkey.pem
        dest: /etc/ssl/privkey.pem
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      delegate_to: 10.1.0.102

